/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import acteurs.Entreprise;
import forms.Convention;
import forms.Stage;

/**
 *
 * @author Guillaume
 */
public class IHM_Entreprise extends javax.swing.JFrame {

    /**
     * Creates new form IHM_Entreprise
     */
    public IHM_Entreprise() {
        this.setObj_entreprise(new Entreprise());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jAjoutIntitule = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAjoutDescription = new javax.swing.JTextArea();
        jEffacer = new javax.swing.JButton();
        jEnvoyer = new javax.swing.JButton();
        jEffacerPanel = new javax.swing.JPanel();
        listeStage = new java.awt.List();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jEffacerIntitule = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEffacerDescription = new javax.swing.JTextArea();
        jSupprimer = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        listeConvention = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jNomEtu = new javax.swing.JTextField();
        jPrenomEtu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jIntituleConv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDescConv = new javax.swing.JTextArea();
        jRefuser = new javax.swing.JButton();
        jSigner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Intitule Stage:");

        jLabel6.setText("Description:");

        jAjoutDescription.setColumns(20);
        jAjoutDescription.setRows(5);
        jScrollPane2.setViewportView(jAjoutDescription);

        jEffacer.setText("Effacer");

        jEnvoyer.setText("Envoyer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jEffacer)
                                .addGap(84, 84, 84)
                                .addComponent(jEnvoyer)
                                .addGap(68, 68, 68))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(80, 80, 80)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jAjoutIntitule)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jAjoutIntitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEffacer)
                    .addComponent(jEnvoyer))
                .addGap(39, 39, 39))
        );

        jTabbedPane2.addTab("Ajout Offre Stage", jPanel2);

        jLabel4.setText("Intitulé:");

        jLabel7.setText("Description:");

        jEffacerIntitule.setText("jTextField5");

        jEffacerDescription.setColumns(20);
        jEffacerDescription.setRows(5);
        jScrollPane3.setViewportView(jEffacerDescription);

        jSupprimer.setText("Supprimer");

        javax.swing.GroupLayout jEffacerPanelLayout = new javax.swing.GroupLayout(jEffacerPanel);
        jEffacerPanel.setLayout(jEffacerPanelLayout);
        jEffacerPanelLayout.setHorizontalGroup(
            jEffacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEffacerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeStage, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jEffacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jEffacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEffacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jEffacerIntitule)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(jSupprimer))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jEffacerPanelLayout.setVerticalGroup(
            jEffacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEffacerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeStage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jEffacerPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jEffacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jEffacerIntitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jEffacerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jSupprimer)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Effacer Offre Stage", jEffacerPanel);

        jTabbedPane1.addTab("Gestion Offre de Stage", jTabbedPane2);

        jLabel1.setText("Eutdiant:");

        jNomEtu.setText("jTextField1");
        jNomEtu.setEnabled(false);
        
        jPrenomEtu.setText("jTextField1");
        jPrenomEtu.setEnabled(false);
        
        jLabel2.setText("Intitule Stage:");
        
        jIntituleConv.setText("jTextField1");
        jIntituleConv.setEnabled(false);
        
        jLabel3.setText("Description:");

        jDescConv.setColumns(20);
        jDescConv.setRows(5);
        jScrollPane1.setViewportView(jDescConv);

        jDescConv.setEnabled(false);
        
        jRefuser.setText("Refuser");

        jSigner.setText("Signer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeConvention, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(46, 46, 46)
                            .addComponent(jNomEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPrenomEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jIntituleConv)
                                .addComponent(jScrollPane1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRefuser)
                        .addGap(84, 84, 84)
                        .addComponent(jSigner)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeConvention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNomEtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrenomEtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jIntituleConv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRefuser)
                    .addComponent(jSigner))
                .addGap(39, 39, 39))
        );

        jTabbedPane4.addTab(" ", jPanel1);

        jTabbedPane1.addTab("Gestion Convention", jTabbedPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        
        this.listeConvention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeConventionActionPerformed(evt);
            }
        });
        
        jEffacerIntitule.setEnabled(false);
        jEffacerDescription.setEnabled(false);
        
        this.setTitle(obj_entreprise.getAttr_str_nom());
        
        jEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEffacerActionPerformed(evt);
            }
        });
        
        jEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnvoyerActionPerformed(evt);
            }
        });
        
        tabOffre = new ArrayList<Stage>();
        tabOffre.add(0, new Stage(0,"LES STAGES","",new Entreprise()));
        
        listeStage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeStageActionPerformed(evt);
            }
        });
        
        jSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupprimerActionPerformed(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSupprimerActionPerformed(java.awt.event.ActionEvent evt) {
        
        if(this.listeStage.getSelectedIndex() != 0 && !this.jEffacer.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Offre de stage supprimée.", "Information", JOptionPane.INFORMATION_MESSAGE);
            
            
            this.tabOffre.remove(this.listeStage.getSelectedIndex());
            
            this.jEffacerIntitule.setText("");
            this.jEffacerDescription.setText("");
            
            this.actualiserListeStage();
        }
    }
    
    private void jEffacerActionPerformed(java.awt.event.ActionEvent evt) {
        
        this.jAjoutIntitule.setText("");
        this.jAjoutDescription.setText("");
        
    }
    
    private void jEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {
        
        int s = this.tabOffre.size();
        this.tabOffre.add(new Stage(s, this.jAjoutIntitule.getText(), this.jAjoutDescription.getText(), new Entreprise()));
        
        this.jAjoutIntitule.setText("");
        this.jAjoutDescription.setText("");
        
        actualiserListeStage();
        
    }
    
    private void listeConventionActionPerformed(java.awt.event.ActionEvent evt) {
        
        if(this.listeConvention.getSelectedIndex()!=0){
            this.jPrenomEtu.setText(this.getTabConv().get(listeConvention.getSelectedIndex()).getObj_etudiant().getAttr_str_prenom());
            this.jNomEtu.setText(this.getTabConv().get(listeConvention.getSelectedIndex()).getObj_etudiant().getAttr_str_nom());
            this.jIntituleConv.setText(this.getObj_entreprise().getAttr_list_catalogue().get(this.listeConvention.getSelectedIndex()).getAttr_str_intitule());
            this.jDescConv.setText(this.getObj_entreprise().getAttr_list_catalogue().get(this.listeConvention.getSelectedIndex()).getAttr_str_descOS());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHM_Entreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHM_Entreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHM_Entreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHM_Entreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHM_Entreprise().setVisible(true);
            }
        });
    }
    private void listeStageActionPerformed(java.awt.event.ActionEvent evt) {
        
        int index = this.listeStage.getSelectedIndex();
        //Intitule:
        this.jEffacerIntitule.setText(this.tabOffre.get(index).getAttr_str_intitule());
        //Description:
        this.jEffacerDescription.setText(this.tabOffre.get(index).getAttr_str_descOS());
        
    }

    private void actualiserListeStage(){
        listeStage.removeAll();
        listeStage.add("LES STAGES",0);
        for(int i=1; i< this.tabOffre.size(); i++)
        {
            listeStage.add(tabOffre.get(i).getAttr_str_intitule());
        }

        this.listeStage.select(0);
    };
    
    /**
     * @return the listeDemande
     */
    public ArrayList<Stage> getTabOffre() {
        return tabOffre;
    }

    /**
     * @param listeDemande the listeDemande to set
     */
    public void setTabOffre(ArrayList<Stage> listeDemande) {
        this.tabOffre = listeDemande;
    }

    /**
     * @return the listeConv
     */
    public ArrayList<Convention> getTabConv() {
        return tabConv;
    }

    /**
     * @param listeConv the listeConv to set
     */
    public void setTabConv(ArrayList<Convention> listeConv) {
        this.tabConv = listeConv;
    }

    /**
     * @return the obj_entreprise
     */
    public Entreprise getObj_entreprise() {
        return obj_entreprise;
    }

    /**
     * @param obj_entreprise the obj_entreprise to set
     */
    public void setObj_entreprise(Entreprise obj_entreprise) {
        this.obj_entreprise = obj_entreprise;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAjoutDescription;
    private javax.swing.JTextField jAjoutIntitule;
    private javax.swing.JTextArea jDescConv;
    private javax.swing.JButton jEffacer;
    private javax.swing.JTextArea jEffacerDescription;
    private javax.swing.JTextField jEffacerIntitule;
    private javax.swing.JPanel jEffacerPanel;
    private javax.swing.JButton jEnvoyer;
    private javax.swing.JTextField jIntituleConv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNomEtu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPrenomEtu;
    private javax.swing.JButton jRefuser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jSigner;
    private javax.swing.JButton jSupprimer;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private java.awt.List listeConvention;
    private java.awt.List listeStage;
    private ArrayList<Stage> tabOffre;
    private ArrayList<Convention> tabConv;
    private Entreprise obj_entreprise;
    // End of variables declaration//GEN-END:variables
}
