/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import acteurs.Directeur;
import acteurs.Ecole;
import acteurs.Entreprise;
import acteurs.Etudiant;
import forms.Convention;
import forms.Stage;

/**
 *
 * @author Guillaume
 */
public class IHM_Directeur extends javax.swing.JFrame {

    Entreprise thales;
    Stage the_stage;
    Ecole school;
    Etudiant student;
    Convention ask;
    /**
     * Creates new form IHM_Directeur
     */
    public IHM_Directeur() {
        initComponents();

        thales = new Entreprise(1,"LES CONVENTIONS","","","");
        the_stage = new Stage(1, "LES CONVENTIONS","",thales);
        school = new Ecole() ;
        student = new Etudiant("Charnay","", 1994, "", 1 , school,"");
        ask = new Convention(1, the_stage, student);
        
        this.getCatalogue().add(0, ask);

        thales = new Entreprise(1,"THALES","truc","truc","truc");
        the_stage = new Stage(1, "stage information 3 mois H/F","description blablabla",thales);
        school = new Ecole() ;
        student = new Etudiant("Charnay"," Charnay", 1994, "studies", 1 , school,"prout");
        ask = new Convention(2, the_stage, student);
        
        this.catalogue.add(1, ask);
        
        thales = new Entreprise(2,"Dassault","truc","truc","truc");
        the_stage = new Stage(2, "stage MAth 3 mois H/F","description mqrdkjvklùna^lckgq;j%GECN.²",thales);
        school = new Ecole() ;
        student = new Etudiant("fUCK"," libido", 1994, "studies", 2 , school,"prout");
        ask = new Convention(3, the_stage, student);
        
        this.catalogue.add(2, ask);
        
        
        this.actualiserListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jAccepterButton = new javax.swing.JButton();
        jRefuserButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDescriptionArea = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jlisteDemande = new javax.swing.JScrollPane();
        list1 = new java.awt.List();
        catalogue = new ArrayList<Convention>();
        Director = new Directeur("dir.prenom", "dir.nom", "dir.signature");

        
        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFrame1.setTitle("Demandes de validation d'offre de stage");
        
        jLabel1.setText("Etudiant:");

        jLabel2.setText("Signature:");

        jLabel3.setText("Entreprise:");

        jLabel4.setText("Signature:");

        jAccepterButton.setText("Signer");

        jRefuserButton.setText("Refuser");

        jDescriptionArea.setColumns(20);
        jDescriptionArea.setRows(5);
        jScrollPane1.setViewportView(jDescriptionArea);

        jTextField1.setEnabled(false);
        jTextField1.setText("");

        jTextField2.setEnabled(false);
        jTextField2.setText("");

        jTextField3.setEnabled(false);
        jTextField3.setText("");

        jTextField4.setEnabled(false);
        jTextField4.setText("");
        
        jDescriptionArea.setEnabled(false);
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jRefuserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAccepterButton)
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAccepterButton)
                    .addComponent(jRefuserButton))
                .addGap(23, 23, 23))
        );

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });
        
        jAccepterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcceptActionPerformed(evt);
            }
        });
        
        jRefuserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefusActionPerformed(evt);
            }
        });
        jlisteDemande.setViewportView(list1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlisteDemande, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlisteDemande)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAcceptActionPerformed(java.awt.event.ActionEvent evt) {
    
        if( this.list1.getSelectedIndex() != 0 && !this.jTextField1.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Demade de stage validée.", "Information", JOptionPane.INFORMATION_MESSAGE);
            
            this.getCatalogue().remove(this.list1.getSelectedIndex());
            
            this.catalogue.get(this.list1.getSelectedIndex()).setAttr_signatureDirecteur(Director.getAttr_str_signature());

            this.cleanDisplay();
        }
        this.actualiserListe();
        
    }
    private void jRefusActionPerformed(java.awt.event.ActionEvent evt) {
        
        if(this.list1.getSelectedIndex() != 0 && !this.jTextField1.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Demade de stage refusée.", "Information", JOptionPane.INFORMATION_MESSAGE);
            
            
            this.getCatalogue().remove(this.list1.getSelectedIndex());
            
            this.cleanDisplay();
            
            this.actualiserListe();
        }
    }
    
    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {
        
        int index = this.list1.getSelectedIndex();
        //Etudiant:
        this.jTextField1.setText(this.catalogue.get(index).getObj_etudiant().getAttr_str_nom()+" "+this.catalogue.get(index).getObj_etudiant().getAttr_str_prenom());
        //Intitule:
        this.jTextField2.setText(this.catalogue.get(index).getObj_stage().getAttr_str_intitule());
        //Entreprise
        this.jTextField3.setText(this.catalogue.get(index).getObj_stage().getAttr_str_nomEntreprise());
        //Description
        this.jDescriptionArea.setText(this.catalogue.get(index).getObj_stage().getAttr_str_descOS());
    }
    
    private void actualiserListe(){
        list1.removeAll();
        list1.add("LES CONVENTIONS");
        for(int i=1; i< this.catalogue.size(); i++)
        {
            list1.add(catalogue.get(i).getObj_stage().getAttr_str_nomEntreprise()+"->"+catalogue.get(i).getObj_etudiant().getAttr_str_nom());
        }

        this.list1.select(0);
    };
    
    private void cleanDisplay() {
        
      //Etudiant:
        this.jTextField1.setText("");
        //Intitule:
        this.jTextField2.setText("");
        //Entreprise
        this.jTextField3.setText("");
        //Description
        this.jDescriptionArea.setText("");

        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger( IHM_Directeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger( IHM_Directeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger( IHM_Directeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger( IHM_Directeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHM_Directeur().setVisible(true);
            }
        });
    }

    /**
     * @return the catalogue
     */
    public ArrayList<Convention> getCatalogue() {
        return catalogue;
    }
    
    /**
     * @param catalogue the catalogue to set
     */
    public void setCatalogue(ArrayList<Convention> catalogue) {
        this.catalogue = catalogue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAccepterButton;
    private javax.swing.JTextArea jDescriptionArea;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRefuserButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JScrollPane jlisteDemande;
    private java.awt.List list1;
    private ArrayList<Convention> catalogue;
    private Directeur Director;
    // End of variables declaration//GEN-END:variables
}
