/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import acteurs.Entreprise;
import acteurs.Etudiant;
import forms.Convention;
import forms.Stage;
import jdbc.JDBC_Entreprise;
import jdbc.JDBC_Etudiant;

/**
 *
 * @author Guillaume
 */
public class IHM_Etudiant extends javax.swing.JFrame {

    /**
     * Creates new form IHM_Etudiant
     */
    public IHM_Etudiant() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ongletChoisir = new javax.swing.JPanel();
        listeFavoris1 = new java.awt.List();
        jEntrepriseLabel = new javax.swing.JLabel();
        jEntrepriseField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jIntituleField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDescArea = new javax.swing.JTextArea();
        jAjouter = new javax.swing.JButton();
        jRetirer = new javax.swing.JButton();
        listeEntreprise = new java.awt.List();
        listeStages = new java.awt.List();
        ongletGerer = new javax.swing.JPanel();
        listeFavoris2 = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jFavorisIntitule = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFavorisEntreprise = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDescriptionArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        favoris = new ArrayList<Stage>();

        obj_etu = Etudiant.get(6);

        this.jIntituleField.setEnabled(false);
        this.jDescArea.setEnabled(false);
        this.jEntrepriseField.setEnabled(false);
        this.jFavorisEntreprise.setEnabled(false);
        this.jFavorisIntitule.setEnabled(false);
        this.jDescriptionArea.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEntrepriseLabel.setText("Entreprise");

        jEntrepriseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntrepriseFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Intitule");

        jLabel2.setText("Description");

        jDescArea.setColumns(20);
        jDescArea.setRows(5);
        jScrollPane1.setViewportView(jDescArea);

        jAjouter.setText("Ajouter");

        jRetirer.setText("Retirer");

        javax.swing.GroupLayout ongletChoisirLayout = new javax.swing.GroupLayout(ongletChoisir);
        ongletChoisir.setLayout(ongletChoisirLayout);
        ongletChoisirLayout.setHorizontalGroup(ongletChoisirLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ongletChoisirLayout.createSequentialGroup().addContainerGap()
                        .addGroup(ongletChoisirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(listeEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, 182,
                                        Short.MAX_VALUE)
                                .addComponent(listeStages, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ongletChoisirLayout
                                .createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ongletChoisirLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jEntrepriseLabel).addComponent(jEntrepriseField)
                                        .addComponent(jLabel1).addComponent(jIntituleField).addComponent(jLabel2)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ongletChoisirLayout.createSequentialGroup().addGap(28, 28, 28)
                                        .addComponent(jAjouter).addGap(54, 54, 54).addComponent(jRetirer)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(listeFavoris1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()));
        ongletChoisirLayout.setVerticalGroup(ongletChoisirLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ongletChoisirLayout.createSequentialGroup().addContainerGap().addGroup(ongletChoisirLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ongletChoisirLayout.createSequentialGroup().addGroup(ongletChoisirLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ongletChoisirLayout.createSequentialGroup().addComponent(jEntrepriseLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jEntrepriseField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18).addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jIntituleField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28).addComponent(jLabel2))
                                .addComponent(listeEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, 138,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ongletChoisirLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ongletChoisirLayout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(
                                                        ongletChoisirLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jAjouter).addComponent(jRetirer))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(listeStages, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(listeFavoris1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                        .addContainerGap()));

        jTabbedPane1.addTab("Choisir Favoris", ongletChoisir);

        jLabel3.setText("Intitule:");

        jLabel4.setText("Entreprise:");

        jLabel5.setText("Description:");

        jDescriptionArea.setColumns(20);
        jDescriptionArea.setRows(5);
        jScrollPane3.setViewportView(jDescriptionArea);

        jButton1.setText("DemanderVal");

        jButton2.setText("Lancer Convention");

        jButton3.setText("Annuler Convention");

        javax.swing.GroupLayout ongletGererLayout = new javax.swing.GroupLayout(ongletGerer);
        ongletGerer.setLayout(ongletGererLayout);
        ongletGererLayout.setHorizontalGroup(ongletGererLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ongletGererLayout.createSequentialGroup().addContainerGap()
                        .addComponent(listeFavoris2, javax.swing.GroupLayout.PREFERRED_SIZE, 145,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ongletGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ongletGererLayout.createSequentialGroup().addGap(43, 43, 43)
                                        .addGroup(ongletGererLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3).addComponent(jLabel4).addComponent(jLabel5))
                                        .addGap(73, 73, 73)
                                        .addGroup(ongletGererLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 219,
                                                        Short.MAX_VALUE)
                                                .addComponent(jFavorisIntitule).addComponent(jFavorisEntreprise)))
                                .addGroup(ongletGererLayout.createSequentialGroup().addGap(24, 24, 24)
                                        .addComponent(jButton1).addGap(18, 18, 18).addComponent(jButton2)
                                        .addGap(18, 18, 18).addComponent(jButton3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        ongletGererLayout
                .setVerticalGroup(ongletGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ongletGererLayout.createSequentialGroup().addContainerGap()
                                .addComponent(listeFavoris2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                .addGroup(ongletGererLayout.createSequentialGroup().addGap(32, 32, 32)
                        .addGroup(ongletGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFavorisEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(ongletGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFavorisIntitule, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(ongletGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5).addComponent(jScrollPane3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(ongletGererLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1).addComponent(jButton2).addComponent(jButton3))
                        .addGap(28, 28, 28)));

        jTabbedPane1.addTab("Gerer Favoris", ongletGerer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1));

        jAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjouterActionPerformed(evt);
            }
        });

        jRetirer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetirerActionPerformed(evt);
            }
        });

        listeEntreprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeEntrepriseActionPerformed(evt);
            }
        });
        listeStages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeStagesActionPerformed(evt);
            }
        });
        listeFavoris1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeFavoris1ActionPerformed(evt);
            }
        });
        listeFavoris2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeFavoris2ActionPerformed(evt);
            }
        });

        this.remplirTabCompany();
        this.actualiserListeEntreprise();

        pack();
    }// </editor-fold>

    private void remplirTabCompany() {
        this.tabCompany = new JDBC_Entreprise().selectAll();
    }

    private void remplirTabStage(Entreprise obj_entreprise) {
        this.tabStage = obj_entreprise.getStages();

    }

    private void cleanDisplay() {

        this.jIntituleField.setText("");
        this.jDescArea.setText("");
        this.jDescriptionArea.setText("");
        this.jFavorisIntitule.setText("");
        this.jFavorisEntreprise.setText("");
        this.jEntrepriseField.setText("");

    }

    private void listeEntrepriseActionPerformed(java.awt.event.ActionEvent evt) {

        int index = this.listeEntreprise.getSelectedIndex();

        this.remplirTabStage(this.tabCompany.get(index));

        this.actualiserListeStages();
        this.cleanDisplay();
    }

    private void listeStagesActionPerformed(java.awt.event.ActionEvent evt) {

        int index = this.listeStages.getSelectedIndex();

        // Intitule:
        this.jIntituleField.setText(this.tabStage.get(index).getAttr_str_intitule());
        // Entreprise
        this.jEntrepriseField.setText(this.tabStage.get(index).getEntreprise().getAttr_str_nom());
        // Description
        this.jDescArea.setText(this.tabStage.get(index).getAttr_str_description());
    }

    private void listeFavoris1ActionPerformed(java.awt.event.ActionEvent evt) {

        int index = this.listeFavoris1.getSelectedIndex();

        // Intitule:
        this.jIntituleField.setText(this.favoris.get(index).getAttr_str_intitule());
        // Entreprise
        this.jEntrepriseField.setText(this.favoris.get(index).getEntreprise().getAttr_str_nom());
        // Description
        this.jDescArea.setText(this.favoris.get(index).getAttr_str_description());
    }

    private void listeFavoris2ActionPerformed(java.awt.event.ActionEvent evt) {

        int index = this.listeFavoris2.getSelectedIndex();

        // Intitule:
        this.jFavorisIntitule.setText(this.favoris.get(index).getAttr_str_intitule());
        // Entreprise
        this.jFavorisEntreprise.setText(this.favoris.get(index).getEntreprise().getAttr_str_nom());
        // Description
        this.jDescriptionArea.setText(this.favoris.get(index).getAttr_str_description());
    }

    private void actualiserListeEntreprise() {

        this.listeEntreprise.removeAll();
        this.cleanDisplay();

        for (int i = 0; i < this.tabCompany.size(); i++) {
            this.listeEntreprise.add(this.tabCompany.get(i).getAttr_str_nom());
        }
    }

    private void actualiserFavoris() {

        this.listeFavoris1.removeAll();
        this.listeFavoris2.removeAll();

        this.cleanDisplay();

        for (int i = 0; i < this.favoris.size(); i++) {
            this.listeFavoris1.add(this.favoris.get(i).getAttr_str_intitule());
            this.listeFavoris2.add(this.favoris.get(i).getAttr_str_intitule());
        }
    }

    private void actualiserListeStages() {
        this.listeStages.removeAll();
        for (int i = 0; i < this.tabStage.size(); i++) {
            this.listeStages.add(this.tabStage.get(i).getAttr_str_intitule());

        }
    }

    private void jAjouterActionPerformed(java.awt.event.ActionEvent evt) {

        if (!this.jIntituleField.getText().isEmpty()) {

            this.favoris.add(this.tabStage.get(this.listeStages.getSelectedIndex()));

            int index = this.favoris.size();
            this.listeFavoris1.add(favoris.get(index - 1).getAttr_str_intitule());

            Convention conv_sta = new Convention(favoris.get(favoris.size() - 1).getAttr_int_idSt(),
                    obj_etu.getAttr_int_idUt(), false, false, false, false);

            conv_sta.create();

            this.cleanDisplay();
        }
        this.actualiserFavoris();
        this.actualiserListeStages();

    }

    private void jRetirerActionPerformed(java.awt.event.ActionEvent evt) {

        if (!this.jIntituleField.getText().isEmpty() && this.favoris.size() != 0) {

            this.cleanDisplay();

            this.listeFavoris1.remove(this.favoris.size() - 1);
            this.favoris.remove(this.favoris.size() - 1);
        }
        this.actualiserListeStages();

    }

    private void jEntrepriseFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting
        // code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
         * html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHM_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHM_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHM_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHM_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHM_Etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jAjouter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextArea jDescArea;
    private javax.swing.JTextArea jDescriptionArea;
    private javax.swing.JTextField jEntrepriseField;
    private javax.swing.JLabel jEntrepriseLabel;
    private javax.swing.JTextField jFavorisEntreprise;
    private javax.swing.JTextField jFavorisIntitule;
    private javax.swing.JTextField jIntituleField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jRetirer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.List listeEntreprise;
    private java.awt.List listeFavoris1;
    private java.awt.List listeFavoris2;
    private java.awt.List listeStages;
    private javax.swing.JPanel ongletChoisir;
    private javax.swing.JPanel ongletGerer;
    private ArrayList<Stage> tabStage;
    private ArrayList<Stage> favoris;
    private ArrayList<Entreprise> tabCompany;
    private Etudiant obj_etu;

    // End of variables declaration
}
