package ihm;

import java.awt.event.*;
import java.util.logging.*;

import javax.swing.*;

/**
 *
 * @author Guillaume
 */
public class Menu extends JFrame {

	/**
	 * Creates new form Menu
	 */
	public Menu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jEntreprise = new JButton();
		jDirecteur = new JButton();
		jCommission = new JButton();
		jEtudiant = new JButton();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jEntreprise.setText("Entreprise");

		jDirecteur.setText("Directeur");

		jCommission.setText("Commission");

		jEtudiant.setText("Etudiant");

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(19, 19, 19)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(jDirecteur, GroupLayout.PREFERRED_SIZE, 182,
												GroupLayout.PREFERRED_SIZE)
								.addComponent(jEtudiant, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
								.addComponent(jCommission, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
								.addComponent(jEntreprise, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE))
				.addContainerGap(24, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(24, Short.MAX_VALUE)
										.addComponent(jEtudiant, GroupLayout.PREFERRED_SIZE, 46,
												GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jDirecteur, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jEntreprise, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jCommission, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		jEtudiant.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jEtudiantActionPerformed(evt);
			}
		});

		jDirecteur.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jDirecteurActionPerformed(evt);
			}
		});

		jEntreprise.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jEntrepriseActionPerformed(evt);
			}
		});

		jCommission.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jCommissionActionPerformed(evt);
			}
		});

		pack();
	}// </editor-fold>

	private void jEtudiantActionPerformed(ActionEvent evt) {

		/** TODO: IHM_ETUDIANT **/

	}

	private void jDirecteurActionPerformed(ActionEvent evt) {

		this.setVisible(false);
		IHM_Directeur ihm_directeur = new IHM_Directeur();
		ihm_directeur.setVisible(true);

	}

	private void jCommissionActionPerformed(ActionEvent evt) {

		this.setVisible(false);
		IHM_Commission ihm_commission = new IHM_Commission();
		ihm_commission.setVisible(true);

	}

	private void jEntrepriseActionPerformed(ActionEvent evt) {

		this.setVisible(false);
		IHM_Entreprise ihm_entreprise = new IHM_Entreprise();
		ihm_entreprise.setVisible(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Menu().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private JButton jCommission;
	private JButton jDirecteur;
	private JButton jEntreprise;
	private JButton jEtudiant;
	// End of variables declaration
}
